# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
